// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2_2-4GZ4Jf6qfZ3sYVm5KA4sj5WCf6I',
    appId: '1:228813553152:web:723a53097c0928da0c62e5',
    messagingSenderId: '228813553152',
    projectId: 'mobile-course-c2353',
    authDomain: 'mobile-course-c2353.firebaseapp.com',
    storageBucket: 'mobile-course-c2353.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN01WrTQUqBbu2Y3R9N7jDw7w5f7KnfvE',
    appId: '1:228813553152:android:b3dca25426aefeb70c62e5',
    messagingSenderId: '228813553152',
    projectId: 'mobile-course-c2353',
    storageBucket: 'mobile-course-c2353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYTVEL3MxVUAv_zSATRXevpIYjsQAaoSA',
    appId: '1:228813553152:ios:563432610f1873000c62e5',
    messagingSenderId: '228813553152',
    projectId: 'mobile-course-c2353',
    storageBucket: 'mobile-course-c2353.appspot.com',
    iosClientId: '228813553152-9uitqleqq9d6olggf6m207rmphb7qivj.apps.googleusercontent.com',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYTVEL3MxVUAv_zSATRXevpIYjsQAaoSA',
    appId: '1:228813553152:ios:563432610f1873000c62e5',
    messagingSenderId: '228813553152',
    projectId: 'mobile-course-c2353',
    storageBucket: 'mobile-course-c2353.appspot.com',
    iosClientId: '228813553152-9uitqleqq9d6olggf6m207rmphb7qivj.apps.googleusercontent.com',
    iosBundleId: 'com.example.course',
  );
}
